export default {
  body: {
    margin: 0,
    padding: 0,
    fontFamily: "'PT Sans'",
  },
  html: {
    margin: 0,
    padding: 0,
    fontFamily: "'PT Sans'",
  },
  webkit_scrollbar: {
    display: 'none',
  },
  wrapper: {
    width: '100vw',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    backgroundImage: "url('/images/background.png')",
    backgroundSize: 'cover',
    minHeight: '100vh',
  },
  input_container: {
    borderRadius: '10px',
    backgroundColor: '#ffc1c1',
    width: '80vw',
    zIndex: 1,
    padding: '2rem',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: '3rem',
  },
  main_heading: {
    fontSize: '2.2rem',
    fontWeight: 'lighter',
    textAlign: 'center',
    margin: 0,
    marginTop: '1rem',
    fontFamily: 'PT Sans',
  },
  subheading: {
    fontSize: '1.55rem',
    fontWeight: 'lighter',
    textAlign: 'center',
    textShadow: '0px 3px 4px #00000060',
    margin: 0,
    marginBottom: '20px',
    fontFamily: 'PT Sans',
  },
  next_button: {
    borderRadius: '15px',
    backgroundColor: '#7e5b5b',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    border: 'none',
    boxShadow: '0px 4px 4px 0 #00000025',
    padding: '5px 1.5rem',
  },

  arrow: {
    height: '15px',
    width: '32px',
    marginLeft: '0.8rem',
  },
  inputs_wrapper: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
  },
  field_container: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    margin: '1rem 0',
  },
  input_label: {
    fontSize: '1.1rem',
    minWidth: '55%',
    marginRight: '5%',
  },
  input_field: {
    border: '2px solid black',
    borderRadius: '4px',
    padding: '0.5rem 0.8rem',
    minWidth: '40%',
  },
  sub_input_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '48%',
  },
  radio_container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '70%',
    margin: '0rem 0',
  },
  radio_group: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '120px',
    marginLeft: '30px',
    fontFamily: 'PT Sans',
  },
  required: {
    color: 'red',
    fontSize: '1.5rem',
    marginLeft: '2px',
  },
  info_button: {
    borderRadius: '15px',
    backgroundColor: '#7e5b5b',
    boxSizing: 'border-box',
    display: 'inline',
    color: 'white',
    fontSize: '12px',
    border: 'none',
    boxShadow: '0px 4px 4px 0 #00000025',
    fontWeight: '900',
    marginLeft: '10px',
    cursor: 'pointer',
    fontFamily: 'serif',
  },
  '@media (max-width: 900px)': {
    __expression__: '(max-width: 900px)',
    subheading: {
      marginBottom: '20px',
    },
    inputs_wrapper: {
      flexDirection: 'column',
    },
    field_container: {
      width: '150%',
    },
  },
  '@media (min-width: 1080px)': {
    __expression__: '(min-width: 1080px)',
    inputs_wrapper: {
      gap: '5rem',
    },
  },
  container: {
    marginRight: 'auto',
    marginLeft: 'auto',
    flexDirection: 'column',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '1vh',
    width: '75%',
    fontFamily: 'PT Sans',
    borderRadius: '5px',
  },
  table: {
    width: '100%',
    border: '2px solid #ff3e3e',
    borderRadius: '5px',
  },
  table_header: {
    display: 'flex',
    background: '#ff6c6c',
    padding: '18px 0',
    justifyContent: 'space-around',
    width: '100%',
  },
  table_row: {
    display: 'flex',
    width: '100%',
    padding: '0 0',
  },
  table_data: {
    flex: '1 1 20%',
    textAlign: 'center',
    padding: '13px 0',
    fontSize: '1.1rem',
  },
  header__item: {
    fontSize: '1.3rem',
    fontWeight: 'bold',
  },
  even: {
    backgroundColor: '#ffd1d1',
  },
  odd: {
    backgroundColor: '#ffe0e0',
  },
  buttons: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '1rem 0',
    alignItems: 'center',
    gap: '2rem',
  },
  sub2: {
    fontSize: '2.2rem',
  },
  container2: {
    marginRight: 'auto',
    marginLeft: 'auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '75%',
    fontFamily: "'PT Sans'",
    borderRadius: '5px',
    fontSize: '5px',
  },
}
